YY.Needle.Web/Controllers/Average3DController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YY.Needle.Application.Interfaces;
using YY.Needle.Domain.DTO.Average3D;
using YY.Needle.Web.Models;

namespace YY.Needle.Web.Controllers
{
    public class Average3DController : BaseController
    {
        private readonly IAverage3DAppService _average3dAppService;

        public Average3DController(IAverage3DAppService average3dAppService)
        {
            _average3dAppService = average3dAppService;

        }
        // GET: Average3D
        public ActionResult Index()
        {
            if(CurrentAccountInfo == null)
            {
                return View("/Account/Index");
            }
            return View();
        }

        public JsonResult GetTableData(int pageIndex, int pageSize)
        {
            int total = 0;
            var result = _average3dAppService.GetPage(pageSize, pageIndex, out total);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RunAverage()
        {
            _average3dAppService.RunAverage();
            var result = new ResultJson<string>();
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ViewResult Echarts()
        {
            return View();
        }

        public JsonResult GetEchartsBar()
        {
            var list= _average3dAppService.GetEchartsBarTwo();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ViewResult StepListShow()
        {
            return View();
        }

        public JsonResult GetStepList(string stepName)
        {
            StepEnum step = StepEnum.AvgTwo;
            switch (stepName)
            {
                case "avgTwo":
                    step = StepEnum.AvgTwo;
                    break;
                case "avgFour":
                    step = StepEnum.AvgFour;
                    break;
                case "avgEight":
                    step = StepEnum.AvgEight;
                    break;
            }
            var list = _average3dAppService.GetStepList(step);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

YY.Needle.Web/Controllers/Lottery3DController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YY.Needle.Application.Interfaces;
using YY.Needle.Domain.Entities;

namespace YY.Needle.Web.Controllers
{
  

   // [Authorize(Roles = "Administrator")]
    public class Lottery3DController : Controller
    {
        private readonly ILottery3DAppService _lottery3dAppService;

        public Lottery3DController(ILottery3DAppService lottery3dAppService)
        {
            _lottery3dAppService = lottery3dAppService;
           
        }

        //
        // GET: /StoreManager/

        public ViewResult Index()
        {
            
            return View();
        }

        public JsonResult GetTableData(int pageIndex, int pageSize)
        {
            int total = 0;
            var result = _lottery3dAppService.GetPage(pageSize, pageIndex, out total);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //
        // GET: /StoreManager/Details/5

        //public ViewResult Details(int id)
        //{
        //    var album = _lottery3dAppService.Get(id, @readonly: true);
        //    return View(album);
        //}

        //
        // GET: /StoreManager/Create

        public ActionResult Create()
        {
            //ViewBag.GenreId = new SelectList(_genreAppService.All(@readonly: true), "GenreId", "Name");
            //ViewBag.ArtistId = new SelectList(_artistAppService.All(@readonly: true), "ArtistId", "Name");
            return View();
        }

        //
        // POST: /StoreManager/Create

        [HttpPost]
        public ActionResult Create(Lottery3D album)
        {
            if (ModelState.IsValid)
            {
                var validationResult = _lottery3dAppService.Create(album);

                if (validationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var error in validationResult.Errors)
                    ModelState.AddModelError("", error.Message);
            }

          
            return View(album);
        }

        //
        // GET: /StoreManager/Edit/5

        //public ActionResult Edit(int id)
        //{
        //    var album = _lottery3dAppService.Get(id, @readonly: true);
        //    //ViewBag.GenreId = new SelectList(_genreAppService.All(@readonly: true), "GenreId", "Name", album.GenreId);
        //    //ViewBag.ArtistId = new SelectList(_artistAppService.All(@readonly: true), "ArtistId", "Name", album.ArtistId);
        //    return View(album);
        //}

        //
        // POST: /StoreManager/Edit/5

        [HttpPost]
        public ActionResult Edit(Lottery3D album)
        {
            if (ModelState.IsValid)
            {
                var validationResult = _lottery3dAppService.Update(album);

                if (validationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var error in validationResult.Errors)
                    ModelState.AddModelError("", error.Message);

                return View(album);
            }
            //ViewBag.GenreId = new SelectList(_genreAppService.All(@readonly: true), "GenreId", "Name", album.GenreId);
            //ViewBag.ArtistId = new SelectList(_artistAppService.All(@readonly: true), "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // GET: /StoreManager/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    var album = _lottery3dAppService.Get(id, @readonly: true);
        //    return View(album);
        //}

        //
        // POST: /StoreManager/Delete/5

        //[HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    var album = _lottery3dAppService.Get(id);
        //    _lottery3dAppService.Remove(album);

        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            _lottery3dAppService.Dispose();
            //_artistAppService.Dispose();
            //_genreAppService.Dispose();

            base.Dispose(disposing);
        }
    }
}

YY.Needle.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("歪歪乐", "StepListShow", "Average3D", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Lottery3D")</li>
                    <li>@Html.ActionLink("平均法", "Index", "Average3D")</li>
                    <li>@Html.ActionLink("统计图", "Echarts", "Average3D")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 歪歪乐</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

YY.Needle.Web/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/content/site")
</head>
<body>
    <div id="header">
        <h1><a href="/">ASP.NET MVC MUSIC STORE</a></h1>
        <ul id="navlist">
            <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
            <li><a href="@Url.Content("~/Store/")">Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
        </ul>
    </div>
    @{Html.RenderAction("GenreMenu", "Store");}
    <div id="main">
        @RenderBody()
    </div>
    <div id="footer">
        built with 歪歪乐翻天</a>
    </div>
    @Scripts.Render("~/scripts/jquery")
</body>
</html>